Account Page cleanup (with tabs)
orbiting/republik-frontend pull request #702
Opened 2021-12-10 16:39 UTC by ovbm

2022-01-03 12:15 UTC, felixmichel commented
I am not sure if the padded and grey background is neccessary, I prefer it this way:

![Bildschirmfoto 2022-01-03 um 11 30 28](https://user-images.githubusercontent.com/11921821/147929244-a8082f56-4503-4565-b16c-a5ac5d3a5272.png)

2022-01-03 12:16 UTC, felixmichel commented
I am not sure about the wording here: «Ihr Leseverhalten wird aufgezeichnet» sounds very strong. What are we doing exactly? Only saving the position
![Bildschirmfoto 2022-01-03 um 11 32 57](https://user-images.githubusercontent.com/11921821/147929374-b84a335f-538b-475d-ba5c-129d74250c28.png)
?

2022-01-03 12:17 UTC, felixmichel commented
I dont get thi
![Bildschirmfoto 2022-01-03 um 11 33 41](https://user-images.githubusercontent.com/11921821/147929432-d3fbb671-5812-4593-bfcb-d46877c8e58c.png)
s

2022-01-03 12:17 UTC, felixmichel commented
there is a point missin
![Bildschirmfoto 2022-01-03 um 11 33 50](https://user-images.githubusercontent.com/11921821/147929466-0e8b85b8-2ab1-4139-9c63-6a367e674909.png)
g

2022-01-03 12:29 UTC, felixmichel commented on lib/translations.json
> +      "value": "E-mail-Newsletter abonnieren"
should be E-Mail-Newsletter

2022-01-03 12:49 UTC, felixmichel commented
Missing in Einstellungen:
![Bildschirmfoto 2022-01-03 um 13 49 16](https://user-images.githubusercontent.com/11921821/147932435-b6204d15-c9f2-4460-9cf7-12875c09ea93.png)

2022-01-03 13:35 UTC, felixmichel commented on components/Account/Elements.js
> +import Link from 'next/link'
I think that can be removed

2022-01-03 13:35 UTC, felixmichel commented on components/Account/Elements.js
> +export const EditButton = ({ children, onClick, href }) => {
href prop is not used

2022-01-03 13:49 UTC, felixmichel commented on components/Notifications/Settings.js
>  import Link from 'next/link'
```suggestion
```

2022-01-03 13:50 UTC, felixmichel commented on components/Notifications/Settings.js
> +import NotificationFeedMini from '../../components/Notifications/NotificationFeedMini'
```suggestion
```

2022-01-03 13:50 UTC, felixmichel commented on components/Account/Elements.js
> +import Link from 'next/link'
```suggestion
```

2022-01-03 13:51 UTC, felixmichel commented on components/Account/Elements.js
> +export const EditButton = ({ children, onClick, href }) => {
```suggestion
export const EditButton = ({ children, onClick }) => {
```

2022-01-03 13:53 UTC, felixmichel commented on lib/translations.json
> +      "value": "E-mail-Newsletter abonnieren"
```suggestion
      "value": "E-Mail-Newsletter abonnieren"
```

2022-01-03 13:58 UTC, felixmichel commented on pages/konto/einstellungen.js
> +import { Interaction } from '@project-r/styleguide'
```suggestion
```

2022-01-03 14:01 UTC, felixmichel reviewed
looks good and works 👍 maybe some additional review from @tpreusse, @annatraussnig or @trm217 to check whether it could be merged or not

2022-01-06 10:33 UTC, ovbm commented
> I am not sure if the padded and grey background is neccessary, I prefer it this way:
> 
> ![Bildschirmfoto 2022-01-03 um 11 30 28](https://user-images.githubusercontent.com/11921821/147929244-a8082f56-4503-4565-b16c-a5ac5d3a5272.png)

agreed

2022-01-10 08:23 UTC, tpreusse requested changes

2022-01-11 15:11 UTC, ovbm commented on pages/konto/transaktionen.js
> +        <AccountSection id='newsletter' title={t('account/transactions/title')}>
It would be inconsistent if this section didn't have a section title. All other sections do.

2022-01-11 15:19 UTC, ovbm commented on pages/konto/abo.js
> +      {postPledge && <Merci query={query} />}
✔️

2022-01-11 15:26 UTC, ovbm commented on components/Account/NewsletterSubscriptions/index.js
> +                        status={status}
uh i like this :D, probably need to be able to remove the title and description if it's not on the account page.

2022-01-11 15:46 UTC, ovbm commented on pages/konto/index.js
> +
how do I find the links with hashes we've previously used? when searching through the code and translations.json, I can't find any `/konto#hash` links except one `/konto#abo` link, which is covered.

2022-01-11 15:47 UTC, tpreusse commented on pages/konto/index.js
> +
The most relevant ones are in the backend transactionals:
https://github.com/orbiting/backends/search?q=%2Fkonto

2022-01-13 09:45 UTC, ovbm commented on components/Account/NewsletterSubscriptions/index.js
> +                        status={status}
<img width="700" alt="Screenshot 2022-01-13 at 10 45 08" src="https://user-images.githubusercontent.com/20746301/149305913-da328aad-4274-4ba1-a284-c0f838e2e416.png">
fixed

2022-01-13 09:45 UTC, ovbm commented on components/Account/NewsletterSubscriptions/NewsletterIcon.js
> +}
deleted

2022-01-13 09:45 UTC, ovbm commented on components/Account/NewsletterSubscriptions/index.js
> +            Sie über die neusten Beiträge.
waiting for com+ for final copy

2022-01-18 07:53 UTC, ovbm commented
copy has been proof read.

2022-01-24 09:53 UTC, tpreusse approved these changes

2022-01-24 10:10 UTC, tpreusse approved these changes

2022-01-24 10:35 UTC, merged